sudo: required
dist: trusty

language: go
go:
  - 1.6.3

services:
  - docker

before_install:
  # Travis was providing 1.12.0 when this was updated last.
  - docker version
  # Sipsak for simulating SIP Register/Deregister
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install sipsak
  - sudo sh -c "echo '127.0.0.1   sip.testserver.tld' >> /etc/hosts"
  # Stuff for Golang
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -covermode=count -coverprofile=profile.cov -v ./...
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
  # - docker ps
  # - docker logs fsregistrator_freeswitch_1
